/**
 * HTML Rendering
 * 
 * Generates the contribution timeline HTML.
 * Supports both full page and embeddable versions.
 */

import { generateYearCalendar } from './aggregate.js';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

/**
 * Generate the complete HTML page
 */
export function renderTimeline({ username, commits, totalCommits, repoCount }) {
  return renderTimelineHTML({ username, commits, totalCommits, repoCount, embed: false });
}

/**
 * Generate embeddable HTML (without header title/theme toggle and footer)
 */
export function renderTimelineEmbed({ username, commits, totalCommits, repoCount }) {
  return renderTimelineHTML({ username, commits, totalCommits, repoCount, embed: true });
}

/**
 * Generate HTML with optional embed mode
 */
function renderTimelineHTML({ username, commits, totalCommits, repoCount, embed = false }) {
  const years = commits.years;
  
  // Generate year sections
  const yearSections = years.map(year => renderYear(year, commits)).join('\n');
  
  // Header content (skip title and theme toggle in embed mode)
  const headerContent = embed ? `
      <div class="username">@${username}</div>
      <div class="stats">
        <div class="stat">
          <span class="stat-value">${totalCommits.toLocaleString()}</span>
          <span>commits</span>
        </div>
        <div class="stat">
          <span class="stat-value">${repoCount}</span>
          <span>repositories</span>
        </div>
        <div class="stat">
          <span class="stat-value">${years.length}</span>
          <span>years</span>
        </div>
      </div>` : `
      <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle theme">
        🌙
      </button>
      <h1>Git History Timeline</h1>
      <div class="username">@${username}</div>
      <div class="stats">
        <div class="stat">
          <span class="stat-value">${totalCommits.toLocaleString()}</span>
          <span>commits</span>
        </div>
        <div class="stat">
          <span class="stat-value">${repoCount}</span>
          <span>repositories</span>
        </div>
        <div class="stat">
          <span class="stat-value">${years.length}</span>
          <span>years</span>
        </div>
      </div>`;
  
  // Footer content (skip in embed mode)
  const footerContent = embed ? '' : `
    <footer>
      <p>Generated by <a href="https://github.com/kibotu/git-history-timeline">git-history-timeline</a></p>
      <p>Every commit counts. Keep shipping. 🚀</p>
    </footer>`;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
  <meta http-equiv="Pragma" content="no-cache">
  <meta http-equiv="Expires" content="0">
  <title>Git History Timeline — @${username}</title>
  <style>
    :root {
      --bg-primary: #0d1117;
      --bg-secondary: #161b22;
      --bg-tertiary: #21262d;
      --text-primary: #f0f6fc;
      --text-secondary: #8b949e;
      --text-muted: #6e7681;
      --border-color: #30363d;
      --accent: #58a6ff;
      
      /* Contribution colors - visible on dark background */
      --level-0: #21262d;
      --level-1: #0e4429;
      --level-2: #006d32;
      --level-3: #26a641;
      --level-4: #39d353;
      
      --cell-size: 11px;
      --cell-gap: 3px;
      --cell-radius: 2px;
    }

    [data-theme="light"] {
      --bg-primary: #ffffff;
      --bg-secondary: #f6f8fa;
      --bg-tertiary: #eaeef2;
      --text-primary: #1f2328;
      --text-secondary: #656d76;
      --text-muted: #57606a;
      --border-color: #d0d7de;
      --accent: #0969da;
      
      --level-0: #ebedf0;
      --level-1: #9be9a8;
      --level-2: #40c463;
      --level-3: #30a14e;
      --level-4: #216e39;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    html {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    }

    body {
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.5;
      min-height: ${embed ? 'auto' : '100vh'};
      padding: 1rem;
    }

    .container {
      max-width: 900px;
      margin: 0 auto;
    }

    /* Theme toggle */
    .theme-toggle {
      position: fixed;
      top: 0.75rem;
      right: 0.75rem;
      background: var(--bg-secondary);
      border: 1px solid var(--border-color);
      border-radius: 6px;
      padding: 0.4rem 0.5rem;
      cursor: pointer;
      font-size: 1rem;
      line-height: 1;
      z-index: 1000;
      transition: all 0.15s ease;
    }

    .theme-toggle:hover {
      border-color: var(--accent);
      background: var(--bg-tertiary);
    }

    /* Header */
    header {
      text-align: center;
      padding: 1.5rem 0 2rem;
      margin-bottom: 1.5rem;
      border-bottom: 1px solid var(--border-color);
    }

    h1 {
      font-size: 1.75rem;
      font-weight: 700;
      margin-bottom: 0.25rem;
      color: var(--text-primary);
    }

    .username {
      font-family: 'SF Mono', Monaco, Menlo, Consolas, monospace;
      font-size: 1rem;
      color: var(--accent);
      margin-bottom: 0.75rem;
    }

    .stats {
      display: flex;
      justify-content: center;
      gap: 1.25rem;
      color: var(--text-secondary);
      font-size: 0.85rem;
    }

    .stat {
      display: flex;
      align-items: center;
      gap: 0.3rem;
    }

    .stat-value {
      font-weight: 600;
      color: var(--text-primary);
      font-family: 'SF Mono', Monaco, Menlo, Consolas, monospace;
    }

    /* Timeline with vertical line */
    .timeline {
      position: relative;
      padding-left: 1.5rem;
    }

    .timeline::before {
      content: '';
      position: absolute;
      left: 0;
      top: 0;
      bottom: 0;
      width: 2px;
      background: linear-gradient(to bottom, var(--accent), var(--level-3), var(--border-color));
      border-radius: 1px;
    }

    /* Year section */
    .year-section {
      position: relative;
      margin-bottom: 2.5rem;
    }

    .year-section::before {
      content: '';
      position: absolute;
      left: -1.5rem;
      top: 0.5rem;
      width: 10px;
      height: 10px;
      background: var(--bg-primary);
      border: 2px solid var(--accent);
      border-radius: 50%;
      transform: translateX(-50%);
    }

    .year-header {
      display: flex;
      align-items: baseline;
      gap: 0.6rem;
      margin-bottom: 0.75rem;
    }
    
    /* Align year header with the left edge of the centered graph container */
    .year-section {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    
    .year-section .year-header {
      align-self: flex-start;
    }

    .year-title {
      font-size: 1.25rem;
      font-weight: 600;
      color: var(--text-primary);
      font-family: 'SF Mono', Monaco, Menlo, Consolas, monospace;
    }

    .year-count {
      font-size: 0.85rem;
      color: var(--text-secondary);
    }

    /* Contribution graph - centered, fit content */
    .graph-container {
      background: var(--bg-secondary);
      border: 1px solid var(--border-color);
      border-radius: 6px;
      padding: 0.75rem;
      display: table; /* Shrink to fit content */
      margin: 0 auto; /* Center horizontally */
    }

    .graph {
      display: flex;
      flex-direction: column;
      gap: 0;
    }

    .months-row {
      display: flex;
      margin-left: 28px;
      gap: var(--cell-gap);
      margin-bottom: 4px;
    }

    .month-label {
      font-size: 0.7rem;
      color: var(--text-muted);
      font-family: 'SF Mono', Monaco, Menlo, Consolas, 'Liberation Mono', 'Courier New', monospace;
    }

    .graph-body {
      display: flex;
      gap: 0;
    }

    .day-labels {
      display: flex;
      flex-direction: column;
      gap: var(--cell-gap);
      margin-right: 4px;
      width: 24px;
      flex-shrink: 0;
    }

    .day-label {
      height: var(--cell-size);
      font-size: 0.65rem;
      color: var(--text-muted);
      font-family: 'SF Mono', Monaco, Menlo, Consolas, 'Liberation Mono', 'Courier New', monospace;
      display: flex;
      align-items: center;
      visibility: hidden;
    }

    /* Only show Mon, Wed, Fri labels (indices 1, 3, 5) */
    .day-label:nth-child(2),
    .day-label:nth-child(4),
    .day-label:nth-child(6) {
      visibility: visible;
    }

    .weeks {
      display: flex;
      gap: var(--cell-gap);
    }

    .week {
      display: flex;
      flex-direction: column;
      gap: var(--cell-gap);
    }

    .day {
      width: var(--cell-size);
      height: var(--cell-size);
      border-radius: var(--cell-radius);
      background: var(--level-0);
      cursor: pointer;
      transition: transform 0.1s ease, box-shadow 0.1s ease;
      position: relative;
    }

    .day:hover {
      transform: scale(1.3);
      z-index: 10;
      box-shadow: 0 0 6px rgba(88, 166, 255, 0.4);
    }

    .day.outside {
      background: transparent;
      cursor: default;
    }

    .day.outside:hover {
      transform: none;
      box-shadow: none;
    }

    .day.level-1 { background: var(--level-1); }
    .day.level-2 { background: var(--level-2); }
    .day.level-3 { background: var(--level-3); }
    .day.level-4 { background: var(--level-4); }

    /* Tooltip - rendered via JavaScript */
    .tooltip {
      position: fixed;
      background: var(--bg-tertiary);
      color: var(--text-primary);
      padding: 0.4rem 0.6rem;
      border-radius: 6px;
      font-size: 0.7rem;
      font-family: 'SF Mono', Monaco, Menlo, Consolas, 'Liberation Mono', 'Courier New', monospace;
      white-space: pre-wrap;
      max-width: 300px;
      pointer-events: none;
      border: 1px solid var(--border-color);
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.4);
      z-index: 9999;
      opacity: 0;
      transition: opacity 0.1s ease;
    }

    .tooltip.visible {
      opacity: 1;
    }

    /* Legend */
    .legend {
      display: flex;
      align-items: center;
      justify-content: flex-end;
      gap: 0.35rem;
      margin-top: 0.5rem;
      font-size: 0.65rem;
      color: var(--text-muted);
    }

    .legend-cells {
      display: flex;
      gap: 2px;
    }

    .legend-cell {
      width: var(--cell-size);
      height: var(--cell-size);
      border-radius: var(--cell-radius);
    }

    /* Footer */
    footer {
      text-align: center;
      padding: 3rem 0;
      color: var(--text-muted);
      font-size: 0.875rem;
      border-top: 1px solid var(--border-color);
      margin-top: 2rem;
    }

    footer a {
      color: var(--accent);
      text-decoration: none;
    }

    footer a:hover {
      text-decoration: underline;
    }

    /* Responsive - Calculate cell size to fit 52 weeks */
    /* Formula: (screen - padding - dayLabels) / 52 weeks / (cell + gap) */
    
    @media (max-width: 800px) {
      :root {
        --cell-size: 10px;
        --cell-gap: 2px;
      }
      
      body { padding: 0.75rem; }
      
      .timeline { padding-left: 1.25rem; }
      .year-section::before { left: -1.25rem; width: 8px; height: 8px; }
      
      h1 { font-size: 1.5rem; }
      header { padding: 1rem 0 1.5rem; margin-bottom: 1rem; }
    }

    @media (max-width: 650px) {
      :root {
        --cell-size: 8px;
        --cell-gap: 2px;
      }
      
      body { padding: 0.5rem; }
      
      .timeline { padding-left: 1rem; }
      .timeline::before { width: 1px; }
      .year-section::before { left: -1rem; width: 6px; height: 6px; }
      .year-section { margin-bottom: 1.5rem; }
      
      h1 { font-size: 1.25rem; }
      .username { font-size: 0.9rem; }
      .stats { gap: 0.75rem; font-size: 0.75rem; flex-wrap: wrap; }
      
      .year-title { font-size: 1rem; }
      .year-count { font-size: 0.75rem; }
      
      .graph-container { padding: 0.5rem; }
      .day-labels { width: 16px; margin-right: 2px; }
      .day-label { font-size: 0.45rem; }
      .months-row { margin-left: 18px; }
      .month-label { font-size: 0.5rem; }
      .legend { font-size: 0.55rem; }
      
      .theme-toggle { top: 0.4rem; right: 0.4rem; padding: 0.3rem; font-size: 0.85rem; }
      footer { padding: 0.75rem 0; font-size: 0.65rem; }
    }

    @media (max-width: 520px) {
      :root {
        --cell-size: 6px;
        --cell-gap: 1px;
      }
      
      .timeline { padding-left: 0; }
      .timeline::before { display: none; }
      .year-section::before { display: none; }
      
      .day-labels { width: 12px; }
      .months-row { margin-left: 14px; }
      .legend { font-size: 0.5rem; }
    }

    @media (max-width: 400px) {
      :root {
        --cell-size: 5px;
        --cell-gap: 1px;
      }
      
      .day-labels { display: none; }
      .months-row { margin-left: 0; }
      .legend { font-size: 0.45rem; }
    }

    @media (max-width: 340px) {
      :root {
        --cell-size: 4px;
        --cell-gap: 1px;
      }
      
      .months-row { display: none; }
      .graph-container { padding: 0.3rem; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>${headerContent}
    </header>

    <div class="timeline">
      ${yearSections}
    </div>
${footerContent}
  </div>

  <!-- Tooltip element -->
  <div class="tooltip" id="tooltip"></div>

  <script>
    // Theme toggle
    function toggleTheme() {
      const html = document.documentElement;
      const current = html.getAttribute('data-theme');
      const next = current === 'light' ? 'dark' : 'light';
      html.setAttribute('data-theme', next);
      const toggle = document.querySelector('.theme-toggle');
      if (toggle) {
        toggle.textContent = next === 'light' ? '☀️' : '🌙';
      }
      localStorage.setItem('theme', next);
    }

    // Load theme from URL parameter (for embed), localStorage, or default
    const urlParams = new URLSearchParams(window.location.search);
    const themeParam = urlParams.get('theme'); // ?theme=light or ?theme=dark
    
    let theme = null;
    if (themeParam === 'light' || themeParam === 'dark') {
      // URL parameter takes precedence (useful for embedding)
      theme = themeParam;
    } else {
      // Fall back to saved theme
      theme = localStorage.getItem('theme');
    }
    
    if (theme) {
      document.documentElement.setAttribute('data-theme', theme);
      const toggle = document.querySelector('.theme-toggle');
      if (toggle) {
        toggle.textContent = theme === 'light' ? '☀️' : '🌙';
      }
    }

    // Tooltip handling
    const tooltip = document.getElementById('tooltip');
    
    document.querySelectorAll('.day[data-tooltip]').forEach(day => {
      day.addEventListener('mouseenter', (e) => {
        const text = e.target.getAttribute('data-tooltip');
        if (!text) return;
        
        tooltip.textContent = text;
        tooltip.classList.add('visible');
        
        const rect = e.target.getBoundingClientRect();
        const tooltipRect = tooltip.getBoundingClientRect();
        
        let left = rect.left + rect.width / 2 - tooltipRect.width / 2;
        let top = rect.top - tooltipRect.height - 8;
        
        // Keep tooltip on screen
        if (left < 8) left = 8;
        if (left + tooltipRect.width > window.innerWidth - 8) {
          left = window.innerWidth - tooltipRect.width - 8;
        }
        if (top < 8) {
          top = rect.bottom + 8; // Show below if no room above
        }
        
        tooltip.style.left = left + 'px';
        tooltip.style.top = top + 'px';
      });
      
      day.addEventListener('mouseleave', () => {
        tooltip.classList.remove('visible');
      });
    });

    ${embed ? `
    // Auto-resize for embed mode
    function sendHeight() {
      const height = document.documentElement.scrollHeight;
      window.parent.postMessage({ type: 'resize', height: height }, '*');
    }

    // Send height on load and when content changes
    window.addEventListener('load', sendHeight);
    window.addEventListener('resize', sendHeight);
    
    // Send initial height
    sendHeight();
    
    // Observe DOM changes and send height updates
    const observer = new ResizeObserver(sendHeight);
    observer.observe(document.body);
    ` : ''}
  </script>
</body>
</html>`;
}

/**
 * Render a single year section
 */
function renderYear(year, commits) {
  const calendar = generateYearCalendar(year, commits.byYear, commits.yearMaxDaily, commits.reposByDate);
  const yearTotal = commits.yearTotals[year] || 0;
  
  // Generate month labels
  const monthLabels = generateMonthLabels(calendar, year);
  
  // Generate weeks
  const weeksHtml = calendar.map(week => {
    const daysHtml = week.map(day => {
      if (!day.inYear) {
        return '<div class="day outside"></div>';
      }
      
      const repoList = day.repos.length > 0 ? day.repos.join(', ') : '';
      const tooltip = day.count === 0
        ? `No commits on ${formatDate(day.date)}`
        : `${day.count} commit${day.count === 1 ? '' : 's'} on ${formatDate(day.date)}${repoList ? '&#10;' + repoList : ''}`;
      
      return `<div class="day level-${day.level}" data-tooltip="${tooltip}" data-date="${day.date}"></div>`;
    }).join('');
    
    return `<div class="week">${daysHtml}</div>`;
  }).join('');
  
  // Day labels
  const dayLabelsHtml = DAYS.map(d => `<div class="day-label">${d}</div>`).join('');

  return `
    <div class="year-section">
      <div class="year-header">
        <span class="year-title">${year}</span>
        <span class="year-count">${yearTotal.toLocaleString()} commits</span>
      </div>
      <div class="graph-container">
        <div class="graph">
          <div class="months-row">${monthLabels}</div>
          <div class="graph-body">
            <div class="day-labels">${dayLabelsHtml}</div>
            <div class="weeks">${weeksHtml}</div>
          </div>
        </div>
        <div class="legend">
          <span>Less</span>
          <div class="legend-cells">
            <div class="legend-cell" style="background: var(--level-0)"></div>
            <div class="legend-cell" style="background: var(--level-1)"></div>
            <div class="legend-cell" style="background: var(--level-2)"></div>
            <div class="legend-cell" style="background: var(--level-3)"></div>
            <div class="legend-cell" style="background: var(--level-4)"></div>
          </div>
          <span>More</span>
        </div>
      </div>
    </div>`;
}

/**
 * Generate month labels positioned above the correct weeks
 */
function generateMonthLabels(calendar, year) {
  const labels = [];
  let lastMonth = -1;
  
  calendar.forEach((week, weekIndex) => {
    // Find the first day of the year in this week
    const yearDay = week.find(d => d.inYear);
    if (yearDay) {
      const month = parseInt(yearDay.date.split('-')[1]) - 1;
      if (month !== lastMonth) {
        // Calculate approximate width for positioning
        const width = `calc(${weekIndex} * (var(--cell-size) + var(--cell-gap)))`;
        labels.push(`<span class="month-label" style="position: absolute; left: ${width}">${MONTHS[month]}</span>`);
        lastMonth = month;
      }
    }
  });
  
  // Wrap in relative container
  return `<div style="position: relative; height: 1rem; width: calc(${calendar.length} * (var(--cell-size) + var(--cell-gap)))">${labels.join('')}</div>`;
}

/**
 * Format date for tooltip
 */
function formatDate(dateStr) {
  const date = new Date(dateStr + 'T00:00:00Z');
  const month = MONTHS[date.getUTCMonth()];
  const day = date.getUTCDate();
  const year = date.getUTCFullYear();
  return `${month} ${day}, ${year}`;
}
